import { ethers } from "ethers";
import { AgentURI, ClientHandler } from "../src";
import { generateChallenge } from "../src/agentkit/func-utils";
import { DID, Id } from "@iden3/js-iden3-core";
import { AuthDidPayload, ProveOwnerPayload } from "../src/agentkit/types";
import { KmsKeyType } from "@0xpolygonid/js-sdk";

/* eslint-disable no-console */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function verifyAgentResponse(client: ClientHandler, agentResponse: any) {
  const green = "\x1b[32m";
  const reset = "\x1b[0m";

  if (
    !agentResponse ||
    !agentResponse.response ||
    !agentResponse.response.artifacts
  ) {
    throw Error("No response for Did proving");
  }

  await client.verifyAuthResponse(agentResponse.response.artifacts);
  console.log(
    "  ✅ Client successfully verified agent message response: " +
      green +
      ` ${agentResponse.response.artifacts.response}` +
      reset
  );
}

/**
 * Main function to demonstrate interaction with an agent:
 * - Generate keys and DID
 * - Prove ownership of the DID using a challenge-response protocol
 * - Verify the DID authentication attestation from the agent from on-chain data
 * - Record an attestation on-chain about the agent's ownership (owner to agent)
 * - Request ownership of the agent with the previous attestation
 * - Prove ownership of the agent with an attestation from agent to owner
 * - Verify the ownership attestation from on-chain data
 */
async function main() {
  const client = new ClientHandler(
    process.env.AGENT_API_URL as string,
    {
      rpcUrl: process.env.BLOCKCHAIN_RPC_URL as string,
      ethPrivateKey: process.env.ETH_PRIVATE_KEY as string,
      attestationRegistryAddress: process.env
        .ATTESTATION_REGISTRY_CONTRACT_ADDRESS as string,
      authVerifierAddress: process.env.AUTH_VERIFIER_CONTRACT_ADDRESS as string,
      agentDidAuthSchemaId: process.env
        .AGENT_DID_AUTH_ATTESTATION_SCHEMA as string,
      agentOwnershipSchemaId: process.env
        .AGENT_OWNERSHIP_ATTESTATION_SCHEMA as string,
      erc8004AttestationSchemaId: process.env
        .ERC8004_ATTESTATION_SCHEMA as string,
    },
    {
      rpcUrl: process.env.ERC8004_BLOCKCHAIN_RPC_URL as string,
      chainId: Number(process.env.ERC8004_CHAIN_ID),
      identityRegistryAddress: process.env
        .ERC8004_IDENTITY_REGISTRY_CONTRACT_ADDRESS as string,
    }
  );

  const wallet = new ethers.Wallet(
    process.env.ETH_PRIVATE_KEY as string,
    new ethers.JsonRpcProvider(process.env.BLOCKCHAIN_RPC_URL as string)
  );

  // Step 1: Ask agent to generate its keys and DID
  const responseFromKeyGeneration = await client.requestGenerateKeysFromAgent();
  await verifyAgentResponse(client, responseFromKeyGeneration);
  console.log(
    `1. Keys generated by agent: \n ${responseFromKeyGeneration.response.response}`
  );

  const balance =
    (await wallet.provider?.getBalance(
      responseFromKeyGeneration.response.artifacts?.ethAddress as string
    )) || 0n;

  const valueEther = process.env.AGENT_FUND_AMOUNT_ETH || "0.0002";

  if (balance < ethers.parseEther(valueEther)) {
    const txFund = await wallet.sendTransaction({
      to: responseFromKeyGeneration.response.artifacts?.ethAddress,
      value: ethers.parseEther(valueEther) - balance,
    });
    await txFund.wait();
    console.log(
      ` 💵 Funded agent address ${responseFromKeyGeneration.response.artifacts?.ethAddress} with ${valueEther} ETH`
    );
  } else {
    console.log(
      ` 💵 Agent address ${
        responseFromKeyGeneration.response.artifacts?.ethAddress
      } has sufficient balance (${ethers.formatEther(balance)} ETH)`
    );
  }

  // Step 2: Ask agent to prove it controls the DID
  // You can pass a specific challenge or omit it to auto-generate one
  const myChallenge = generateChallenge();
  const responseFromDidProving = await client.requestAuthDidFromAgent(
    myChallenge
  );
  await verifyAgentResponse(client, responseFromDidProving);

  console.log(
    `2. Agent's proof response: \n ${responseFromDidProving.response.response}`
  );

  // Step 3: Verify the agent's response to the challenge
  await client.verifyAuthDid(
    responseFromDidProving.response.artifacts as AuthDidPayload
  );
  console.log("3. Agent successfully proved ownership of the DID.");

  // Step 4: Verify attestation on-chain about the agent's DID auth
  console.log(
    `4. User verifies attestation from Agent in attestation registry. Transaction hash: ${
      (responseFromDidProving.response.artifacts as AuthDidPayload).txHash
    }`
  );

  const tx = await wallet.provider?.getTransaction(
    (responseFromDidProving.response.artifacts as AuthDidPayload)
      .txHash as string
  );
  const result = await tx?.wait();
  if (!result) {
    throw new Error("Transaction not found");
  }
  const attestationId = result.logs[0].topics[1];

  console.log(` 🆔 Attestation Id: ${attestationId}`);

  // Step 5. Verify attestation from on-chain attestation registry
  console.log(`5. Verifying attestation from on-chain data.`);
  const attestation = await client.getAttestation(attestationId);
  const decodedData = ethers.AbiCoder.defaultAbiCoder().decode(
    ["uint256", "string", "address", "uint256", "string"],
    attestation.data
  );

  const [
    decodedAgentId,
    decodedAgentDomain,
    decodedAgentAddress,
    decodedChallenge,
    decodedAuthToken,
  ] = decodedData;

  console.log(
    ` 📋 Attestation info decoded from Attestation Registry for attestation Id ${attestation.id}`
  );
  console.log(`   - Schema Id: ${attestation.schemaId}`);
  console.log(`   - Attester DID: ${attestation.attester.did}`);
  console.log(`   - Attester Id: ${attestation.attester.iden3Id}`);
  console.log(`   - Attester Address: ${attestation.attester.ethereumAddress}`);
  console.log(`   - Recipient DID: ${attestation.recipient.did}`);
  console.log(`   - Recipient Id: ${attestation.recipient.iden3Id}`);
  console.log(
    `   - Recipient Address: ${attestation.recipient.ethereumAddress}`
  );
  console.log(`   - Revocable: ${attestation.revocable}`);
  console.log(`   - Reference to other attestation: ${attestation.refId}`);
  console.log(` Decoded data from schema:`);
  console.log(`   - Agent ID: ${decodedAgentId}`);
  console.log(`   - Agent Domain: ${decodedAgentDomain}`);
  console.log(`   - Agent Address: ${decodedAgentAddress}`);
  console.log(`   - Challenge: ${decodedChallenge}`);
  console.log(`   - Auth Token: ${decodedAuthToken}`);

  const decodedDid = DID.parseFromId(Id.fromBigInt(BigInt(decodedAgentId)));

  await client.verifyAuthDid({
    did: decodedDid.string(),
    domain: decodedAgentDomain,
    signedDidAuthToken: decodedAuthToken,
    ethAddress: decodedAgentAddress,
    challenge: decodedChallenge,
    keyType: KmsKeyType.Secp256k1,
    response: "",
    signedResponseToken: "",
  });
  console.log(
    ` ✅ Auth DID Attestation successfully verified from on-chain data.`
  );

  // Step 6: Record an attestation on-chain about the agent's ownership (from the owner to the agent)
  // Note: This step requires the user to be authenticated in the AuthVerifier contract
  const ownershipData = {
    agentId: DID.idFromDID(
      DID.parse(
        (responseFromDidProving.response.artifacts as AuthDidPayload)
          ?.did as string
      )
    )
      .bigInt()
      .toString(),
    agentDomain: (responseFromDidProving.response.artifacts as AuthDidPayload)
      ?.domain as string,
    agentAddress: responseFromDidProving.response.artifacts
      ?.ethAddress as string,
    ownerId: (await client.getUserId()).toString(),
    ownerAddress: await client.getEthereumAddress(),
  };

  const currentUserId = await client.authenticateToAttestationRegistry();
  if (!currentUserId) {
    throw new Error("User authentication to attestation registry failed.");
  }

  const {
    attestationId: ownershipAttestationId,
    txHash: txHashOwnershipAttestationFromOwner,
  } = await client.sendOwnershipAttestation(ownershipData);

  console.log(
    `6. User sent attestation for Agent ownership in attestation registry. Transaction hash: ${txHashOwnershipAttestationFromOwner}`
  );
  console.log(` 🆔 Attestation Id: ${ownershipAttestationId}`);

  // 7. Verify ownership attestation from on-chain attestation registry
  console.log(`7. Verifying ownership attestation from on-chain data.`);
  const ownershipAttestation = await client.getAttestation(
    ownershipAttestationId
  );
  const decodedOwnershipData = ethers.AbiCoder.defaultAbiCoder().decode(
    ["bytes"],
    ownershipAttestation.data
  );

  const [decodedOwnershipBytes] = decodedOwnershipData;

  console.log(
    ` 📋 Attestation info decoded from Attestation Registry for attestation Id ${ownershipAttestationId}`
  );
  console.log(`   - Schema Id: ${ownershipAttestation.schemaId}`);
  console.log(`   - Attester DID: ${ownershipAttestation.attester.did}`);
  console.log(`   - Attester Id: ${ownershipAttestation.attester.iden3Id}`);
  console.log(
    `   - Attester Address: ${ownershipAttestation.attester.ethereumAddress}`
  );
  console.log(`   - Recipient DID: ${ownershipAttestation.recipient.did}`);
  console.log(`   - Recipient Id: ${ownershipAttestation.recipient.iden3Id}`);
  console.log(
    `   - Recipient Address: ${ownershipAttestation.recipient.ethereumAddress}`
  );
  console.log(`   - Revocable: ${ownershipAttestation.revocable}`);
  console.log(
    `   - Reference to other attestation: ${ownershipAttestation.refId}`
  );
  console.log(` Decoded data from schema:`);
  console.log(`   - Bytes: ${decodedOwnershipBytes}`);

  console.log(
    ` ✅ Agent ownership attestation from owner successfully verified from on-chain data.`
  );

  const responseFromOwnershipToAgent = await client.requestOwnershipToAgent(
    txHashOwnershipAttestationFromOwner
  );
  await verifyAgentResponse(client, responseFromOwnershipToAgent);

  console.log(
    `8. Agent's request ownership response: \n ${responseFromOwnershipToAgent.response.response}`
  );

  // Step 9: Ask agent to prove it owner controls the agent
  // (using the previous ownership attestations from owner to agent and from agent to owner)
  const responseProvingOwner = await client.requestOwnerFromAgent();
  await verifyAgentResponse(client, responseProvingOwner);

  console.log(
    `9. Agent's owner response: \n ${responseProvingOwner.response.response}`
  );

  if (!responseProvingOwner.response.artifacts) {
    throw new Error("Missing artifacts in responseProvingOwner");
  }
  const payloadProvingOwner = responseProvingOwner.response
    .artifacts as ProveOwnerPayload;

  // Step 10: Verify the agent's response to the owner proving (from the agent signature)
  const txAgent = await wallet.provider?.getTransaction(
    payloadProvingOwner.txHashAgentAttestation as string
  );
  const resultAgent = await txAgent?.wait();
  if (!resultAgent) {
    throw new Error("Transaction not found");
  }
  const attestationIdAgent = resultAgent.logs[0].topics[1];

  console.log(` 🆔 Attestation Id from Agent: ${attestationIdAgent}`);

  const ownershipAttestationAgent = await client.getAttestation(
    attestationIdAgent
  );
  const decodedOwnershipDataAgent = ethers.AbiCoder.defaultAbiCoder().decode(
    ["bytes"],
    ownershipAttestationAgent.data
  );

  const [decodedOwnershipBytesAgent] = decodedOwnershipDataAgent;

  console.log(
    ` 📋 Attestation info decoded from Attestation Registry for attestation Id ${attestationIdAgent}`
  );
  console.log(`   - Schema Id: ${ownershipAttestationAgent.schemaId}`);
  console.log(`   - Attester DID: ${ownershipAttestationAgent.attester.did}`);
  console.log(
    `   - Attester Id: ${ownershipAttestationAgent.attester.iden3Id}`
  );
  console.log(
    `   - Attester Address: ${ownershipAttestationAgent.attester.ethereumAddress}`
  );
  console.log(`   - Recipient DID: ${ownershipAttestationAgent.recipient.did}`);
  console.log(
    `   - Recipient Id: ${ownershipAttestationAgent.recipient.iden3Id}`
  );
  console.log(
    `   - Recipient Address: ${ownershipAttestationAgent.recipient.ethereumAddress}`
  );
  console.log(`   - Revocable: ${ownershipAttestationAgent.revocable}`);
  console.log(
    `   - Reference to other attestation: ${ownershipAttestationAgent.refId}`
  );
  console.log(` Decoded data from schema:`);
  console.log(`   - Bytes: ${decodedOwnershipBytesAgent}`);

  console.log(
    ` ✅ Agent ownership attestation from agent successfully verified from on-chain data.`
  );
  console.log("10. Agent successfully proved owner.");

  const agentURI: AgentURI = {
    type: "https://eips.ethereum.org/EIPS/eip-8004#registration-v1",
    name: `Billions Agent ${decodedDid.string()}`,
    description:
      "Agent built with Billions Agent JS-SDK using decentralized identity and Billions on-chain attestations",
    image: "",
    services: [
      {
        name: "DID",
        endpoint: decodedDid.string(),
        version: "v1",
      },
    ],
    active: true,
    x402Support: false,
    registrations: [],
    supportedTrust: ["reputation", "attestations"],
    tags: [
      "ethereum",
      "billions",
      "trust",
      "did",
      "attestations",
      "privadoID",
      "iden3",
    ],
  };
  const agentId = await client.registerAgentERC8004(agentURI);
  console.log(
    `11. Agent registered with ERC-8004 with Agent ID: ${agentId.toString()}`
  );
  console.log(` 🆔 ERC8004 Agent ID: ${agentId.toString()}`);

  agentURI.registrations = [
    {
      agentId: Number(agentId),
      agentRegistry: `eip155:${process.env.ERC8004_CHAIN_ID as string}:${
        process.env.ERC8004_IDENTITY_REGISTRY_CONTRACT_ADDRESS as string
      }`,
    },
  ];
  await client.setAgentURI(agentId, agentURI);
  console.log(` ✅ set agentURI for Agent ID ${agentId.toString()}`);

  const {
    attestationId: erc8004AttestationId,
    txHash: txHashERC8004AttestationFromOwner,
  } = await client.sendERC8004Attestation(
    agentId.toString(),
    ownershipData.agentId,
    ownershipData.agentAddress,
    ownershipData.ownerId
  );
  console.log(
    `12. User sent attestation for Agent ERC8004 registration in attestation registry. Transaction hash: ${txHashERC8004AttestationFromOwner}`
  );
  console.log(` 🆔 Attestation Id: ${erc8004AttestationId}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
